# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170319_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default=True, upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
